// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlXc6tx9YNGfWogn5zhNXzqKFmloY2iOc',
    appId: '1:233756299057:web:2a877b99e691e5bd9bea10',
    messagingSenderId: '233756299057',
    projectId: 'consultz-e39b8',
    authDomain: 'consultz-e39b8.firebaseapp.com',
    storageBucket: 'consultz-e39b8.firebasestorage.app',
    measurementId: 'G-E69SDWSEG2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoH7OtrHQZPx948VHZi03VlQ3k9aIS3T0',
    appId: '1:233756299057:android:f4c5bf9607f2b3719bea10',
    messagingSenderId: '233756299057',
    projectId: 'consultz-e39b8',
    storageBucket: 'consultz-e39b8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAd8XM2L4rERyTfe1M4sXNBzomeK-ZansA',
    appId: '1:233756299057:ios:1119307b7016c51c9bea10',
    messagingSenderId: '233756299057',
    projectId: 'consultz-e39b8',
    storageBucket: 'consultz-e39b8.firebasestorage.app',
    iosBundleId: 'com.consultzuser.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAd8XM2L4rERyTfe1M4sXNBzomeK-ZansA',
    appId: '1:233756299057:ios:d58b9f1c4aed6b399bea10',
    messagingSenderId: '233756299057',
    projectId: 'consultz-e39b8',
    storageBucket: 'consultz-e39b8.firebasestorage.app',
    iosBundleId: 'com.example.consultz',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAlXc6tx9YNGfWogn5zhNXzqKFmloY2iOc',
    appId: '1:233756299057:web:35debdc1da8fdd0f9bea10',
    messagingSenderId: '233756299057',
    projectId: 'consultz-e39b8',
    authDomain: 'consultz-e39b8.firebaseapp.com',
    storageBucket: 'consultz-e39b8.firebasestorage.app',
    measurementId: 'G-3DLFERZGYM',
  );
}
