import 'package:consultz/feature/Auth/controller/expert_advising_controller.dart';
import 'package:consultz/feature/Auth/controller/expert_session_duration_controller.dart';
import 'package:consultz/feature/Auth/controller/expert_skill_controller.dart';
import 'package:consultz/feature/Auth/controller/forgot_password_controller.dart';
import 'package:consultz/feature/Auth/controller/learning_style_controller.dart';
import 'package:consultz/feature/Auth/controller/price_range_controller.dart';
import 'package:consultz/feature/Auth/controller/profile_controller.dart';
import 'package:consultz/feature/Auth/controller/resend_otp_controller.dart';
import 'package:consultz/feature/Auth/controller/set_expert_bio_controller.dart';
import 'package:consultz/feature/Auth/controller/set_expertise_time_zone_controller.dart';
import 'package:consultz/feature/Auth/controller/set_hourly_rate_controller.dart';
import 'package:consultz/feature/Auth/controller/set_key_expertise_controller.dart';
import 'package:consultz/feature/Auth/controller/set_bank_controller.dart';
import 'package:consultz/feature/Auth/controller/social_profile_controller.dart';
import 'package:consultz/feature/Auth/controller/login_controller.dart';
import 'package:consultz/feature/Auth/controller/sign_up_controller.dart';
import 'package:consultz/feature/Auth/controller/upload_profile_picture_controller.dart';
import 'package:consultz/feature/bookings/controller/expert_booking_controller.dart';
import 'package:consultz/feature/bookings/controller/msg_controller.dart';
import 'package:consultz/feature/bookings/controller/payment_controller.dart';
import 'package:consultz/feature/discover/controller/comment_controller.dart';
import 'package:consultz/feature/discover/controller/content_controller.dart';
import 'package:consultz/feature/discover/controller/discover_controller.dart';
import 'package:consultz/feature/discover/controller/like_controller.dart';
import 'package:consultz/feature/discover/controller/report_controller.dart';
import 'package:consultz/feature/expert/controller/calendar_controller.dart';
import 'package:consultz/feature/expert/controller/edit_expert_category_controller.dart';
import 'package:consultz/feature/expert/controller/edit_expert_language_controller.dart';
import 'package:consultz/feature/expert/controller/edit_expert_sub_category_controller.dart';
import 'package:consultz/feature/expert/controller/expert_dashboard_controller.dart';
import 'package:consultz/feature/expert/controller/expert_detail_controller.dart';
import 'package:consultz/feature/expert/controller/expert_education_controller.dart';
import 'package:consultz/feature/expert/controller/expert_profile_controller.dart';
import 'package:consultz/feature/expert/controller/expert_review_controller.dart';
import 'package:consultz/feature/expert/controller/follow_unfollow_controller.dart';
import 'package:consultz/feature/expert/controller/follower_following_controller.dart';
import 'package:consultz/feature/expert/controller/invite_friend_controller.dart';
import 'package:consultz/feature/expert/controller/profile_share_controller.dart';
import 'package:consultz/feature/expert/controller/terms_condition_controller.dart';
import 'package:consultz/feature/expert/controller/update_expert_bio_controller.dart';
import 'package:consultz/feature/expert/controller/update_expert_image_controller.dart';
import 'package:consultz/feature/expert/controller/update_social_profile_controller.dart';
import 'package:consultz/feature/expert/controller/withdraw_controller.dart';
import 'package:consultz/feature/home/controller/interest_expert_controller.dart';
import 'package:consultz/feature/home/controller/property_expert_controller.dart';
import 'package:consultz/feature/home/controller/search_expert_controller.dart';
import 'package:consultz/feature/home/controller/top_expert_controller.dart';
import 'package:consultz/feature/main/controller/main_controller.dart';
import 'package:consultz/feature/Auth/controller/browse_first_controller.dart';
import 'package:consultz/feature/post/controller/post_controller.dart';
import 'package:consultz/feature/profile/controller/blocked_user_controller.dart';
import 'package:consultz/feature/bookings/controller/booking_details_controller.dart';
import 'package:consultz/feature/profile/controller/booking_history_details_controller.dart';
import 'package:consultz/feature/profile/controller/booking_history_controller.dart';
import 'package:consultz/feature/profile/controller/change_password_controller.dart';
import 'package:consultz/feature/profile/controller/consultee_profile_controller.dart';
import 'package:consultz/feature/profile/controller/notification_setting_controller.dart';
import 'package:consultz/feature/profile/controller/update_consultee_profile_controller.dart';
import 'package:consultz/feature/profile/controller/update_name_controller.dart';
import 'package:consultz/feature/profile/controller/support_controller.dart';
import 'package:consultz/feature/profile/controller/add_payment_method_controller.dart';
import 'package:consultz/feature/profile/controller/payment_details_controller.dart';
import 'package:consultz/feature/bookings/controller/booking_controller.dart';
import 'package:consultz/feature/profile/controller/update_phone_number_controller.dart';
import 'package:consultz/feature/shome_me_expert/controller/show_me_expert_category_controller.dart';
import 'package:consultz/feature/shome_me_expert/controller/show_me_expert_interest_controller.dart';
import 'package:consultz/feature/shome_me_expert/controller/show_me_expert_property_controller.dart';
import 'package:consultz/feature/shome_me_expert/controller/show_me_expert_top_controller.dart';
import 'package:consultz/feature/splash/controller/connection_checker_controller.dart';
import 'package:consultz/feature/filter/controller/filter_controller.dart';
import 'package:consultz/feature/profile/controller/delete_account_controller.dart';
import 'package:consultz/feature/profile/controller/following_controller.dart';
import 'package:consultz/feature/notification/controller/notification_controller.dart';
import 'package:get/get.dart';

class InitDependencyBinding extends Bindings {
  @override
  void dependencies() {
    Get.put(MainController());
    Get.put(BrowseFirstController());
    Get.put(ConsulteeProfileController());
    Get.put(PostController());
    Get.put(ProfileController());
    Get.put(ConnectionCheckerController());
    Get.put(DiscoverController());
    Get.put(InterestExpertController());
    Get.put(PropertyExpertController());
    Get.put(TopExpertController());
    Get.put(ExpertBookingController());
    Get.lazyPut(() => FilterController(), fenix: true);
    Get.lazyPut(() => SearchExpertController(), fenix: true);
    Get.lazyPut(() => LoginController(), fenix: true);
    Get.lazyPut(() => SignUpController(), fenix: true);
    Get.lazyPut(() => ExpertDetailController(), fenix: true);
    Get.lazyPut(() => BookingHistoryController(), fenix: true);
    Get.lazyPut(() => BookingDetailsController(), fenix: true);
    Get.lazyPut(() => BookingHistoryDetailsController(), fenix: true);
    Get.lazyPut(() => FollowerFollowingController(), fenix: true);
    Get.lazyPut(() => ExpertDashboardViewModel(), fenix: true);
    Get.lazyPut(() => UploadProfilePictureController(), fenix: true);
    Get.lazyPut(() => CalendarController(), fenix: true);
    Get.lazyPut(() => SocialProfileController(), fenix: true);
    Get.lazyPut(() => SetHourlyRateController(), fenix: true);
    Get.lazyPut(() => SetBankController(), fenix: true);
    Get.lazyPut(() => SetKeyExpertiseController(), fenix: true);
    Get.lazyPut(() => ExpertSkillController(), fenix: true);
    Get.lazyPut(() => ExpertAdvisingController(), fenix: true);
    Get.lazyPut(() => SetExpertBioController(), fenix: true);
    Get.lazyPut(() => SetExpertiseTimeZoneController(), fenix: true);
    Get.lazyPut(() => ExpertSessionDurationController(), fenix: true);
    Get.lazyPut(() => NotificationSettingController(), fenix: true);
    Get.lazyPut(() => UpdateExpertImageController(), fenix: true);
    Get.lazyPut(() => ExpertReviewController(), fenix: true);
    Get.lazyPut(() => ChangePasswordController(), fenix: true);
    Get.lazyPut(() => UpdateNameController(), fenix: true);
    Get.lazyPut(() => UpdateExpertBioController(), fenix: true);
    Get.lazyPut(() => EditExpertCategoryController(), fenix: true);
    Get.lazyPut(() => UpdateSocialProfileController(), fenix: true);
    Get.lazyPut(() => EditExpertSubCategoryController(), fenix: true);
    Get.lazyPut(() => ExpertEducationController(), fenix: true);
    Get.lazyPut(() => EditExpertLanguageController(), fenix: true);
    Get.lazyPut(() => BlockedUserController(), fenix: true);
    Get.lazyPut(() => FollowUnfollowController(), fenix: true);
    Get.lazyPut(() => TermsConditionController(), fenix: true);
    Get.lazyPut(() => ContentController(), fenix: true);
    Get.lazyPut(() => CommentController(), fenix: true);
    Get.lazyPut(() => LikeController(), fenix: true);
    Get.lazyPut(() => ExpertProfileController(), fenix: true);
    Get.lazyPut(() => ReportController(), fenix: true);
    Get.lazyPut(() => SupportController(), fenix: true);
    Get.lazyPut(() => AddPaymentMethodController(), fenix: true);
    Get.lazyPut(() => PaymentDetailsController(), fenix: true);
    Get.lazyPut(() => BookingController(), fenix: true);
    Get.lazyPut(() => WithdrawController(), fenix: true);
    Get.lazyPut(() => PaymentController(), fenix: true);
    Get.lazyPut(() => DeleteAccountController(), fenix: true);
    Get.lazyPut(() => PriceRangeController(), fenix: true);
    Get.lazyPut(() => LearningStyleController(), fenix: true);
    Get.lazyPut(() => UpdateConsulteeProfileController(), fenix: true);
    Get.lazyPut(() => FollowingController(), fenix: true);
    Get.lazyPut(() => UpdatePhoneNumberController(), fenix: true);
    Get.lazyPut(() => InviteFriendController(), fenix: true);
    Get.lazyPut(() => NotificationController(), fenix: true);
    Get.lazyPut(() => MsgController(), fenix: true);
    Get.lazyPut(() => ForgotPasswordController(), fenix: true);
    Get.lazyPut(() => ResendOtpController(), fenix: true);
    Get.lazyPut(() => ShowMeExpertCategoryController(), fenix: true);
    Get.lazyPut(() => ShowMeExpertInterestController(), fenix: true);
    Get.lazyPut(() => ShowMeExpertPropertyController(), fenix: true);
    Get.lazyPut(() => ShowMeExpertTopController(), fenix: true);
    Get.lazyPut(() => ProfileShareController(), fenix: true);
  }
}
