final timeZone = [
  'Select a time zone',
  'UTC −12:00 (Baker Island)',
  'UTC −11:00 (Niue, Samoa)',
  'UTC −10:00 (Hawaii)',
  'UTC −9:30 (Marquesas Islands)',
  'UTC −9:00 (Alaska)',
  'UTC −8:00 (Los Angeles, Vancouver)',
  'UTC −7:00 (Denver)',
  'UTC −6:00 (Chicago, Central America)',
  'UTC −5:00 (New York, Toronto)',
  'UTC −4:30 (Venezuela)',
  'UTC −4:00 (Atlantic Time, Caribbean)',
  'UTC −3:30 (Newfoundland)',
  'UTC −3:00 (Brazil, Argentina)',
  'UTC −2:00 (South Georgia)',
  'UTC −1:00 (Azores)',
  'UTC ±0:00 (UK, Ireland, Lisbon)',
  'UTC +1:00 (Paris, Berlin, Spain)',
  'UTC +2:00 (Cairo, South Africa)',
  'UTC +3:00 (Moscow, East Africa)',
  'UTC +3:30 (Iran)',
  'UTC +4:00 (Dubai, Azerbaijan)',
  'UTC +4:30 (Afghanistan)',
  'UTC +5:00 (Pakistan)',
  'UTC +5:30 (India, Sri Lanka)',
  'UTC +5:45 (Nepal)',
  'UTC +6:00 (Bangladesh)',
  'UTC +6:30 (Myanmar)',
  'UTC +7:00 (Thailand, Vietnam)',
  'UTC +8:00 (China, Singapore)',
  'UTC +8:45 (SE Western Australia)',
  'UTC +9:00 (Japan, Korea)',
  'UTC +9:30 (Australia Central)',
  'UTC +10:00 (Sydney, Papua New Guinea)',
  'UTC +10:30 (Lord Howe Island)',
  'UTC +11:00 (Solomon Is, New Caledonia)',
  'UTC +12:00 (New Zealand, Fiji)',
  'UTC +12:45 (Chatham Islands)',
  'UTC +13:00 (Tonga, Samoa DST)',
  'UTC +14:00 (Line Islands)',
];
